# Generated by Django 2.2 on 2020-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0034_auto_20200331_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='html',
            field=models.TextField(default='\n<html>\n<body><p>\nЗдравствуйте, {{assignment.person.first_name}}!<br>\n{{assignment.quiz_structure.name}}<br>\n{{assignment.quiz_structure.minutes}}<br>\n<br>\n{{assignment.quiz_structure.quantity}}<br>\nЛогин: {{assignment.person.user.username}}<br>\nПароль: {{assignment.person.password}}<br>\n</p>\n</body>\n</hmtl>\n        ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(default='\nЗдравствуйте, {{assignment.person.first_name}}! /n\n{{assignment.quiz_structure.name}}/n\n{{assignment.quiz_structure.minutes}}/n\n/n\n{{assignment.quiz_structure.quantity}}/n\nЛогин: {{assignment.person.user.username}}/n\nПароль: {{assignment.person.password}}/n\n    ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
