# Generated by Django 2.2 on 2020-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0036_question_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedquestion',
            name='answer_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='assignedquestion',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
